# monitoring/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'main-server'
    static_configs:
      - targets: ['main-server:3000']
    metrics_path: '/metrics'

  - job_name: 'data-collector'
    static_configs:
      - targets: ['data-collector:8000']
    metrics_path: '/metrics'

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']